# Generated by Django 5.0.2 on 2024-02-22 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderTrack",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "order_date",
                    models.DateField(
                        default=datetime.datetime(
                            2024, 2, 22, 14, 13, 4, 3842, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("sender_name", models.CharField(max_length=100)),
                ("sender_address", models.CharField(max_length=100)),
                ("receiver_name", models.CharField(max_length=100)),
                ("receiver_address", models.CharField(max_length=100)),
                ("receiver_email", models.EmailField(max_length=254)),
                ("receiver_phone", models.CharField(max_length=10)),
                ("tracking_id", models.CharField(max_length=100)),
            ],
        ),
    ]
