# Generated by Django 4.2.10 on 2024-02-29 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordertrack",
            name="order_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 2, 29, 3, 38, 5, 211164, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
